import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";

import "./globals.css";

import { ConvexClientProvider } from "@/components/providers/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import Modals from "@/components/modals";
import { Toaster } from "@/components/ui/sonner";
import JotaiProvider from "@/components/providers/JotaiProvider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
const hasConvex = !!convexUrl && !convexUrl.includes("demo-disabled");

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <ConvexClientProvider>
      <JotaiProvider>
        <Toaster />
        {hasConvex && <Modals />}
        <NuqsAdapter>{children}</NuqsAdapter>
      </JotaiProvider>
    </ConvexClientProvider>
  );

  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        {hasConvex ? (
          <ConvexAuthNextjsServerProvider>{content}</ConvexAuthNextjsServerProvider>
        ) : (
          content
        )}
      </body>
    </html>
  );
}
